### PR TITLE
Added Qualys app and documentation 

### PR DESCRIPTION
**Pull request by dhaval055**

### CODE REVIEW

**Comment by frikky** [comment]
Looks amazing Dhaval. Could you share a Workflow for it as well?

**Comment by dhaval055** [comment]
> Looks amazing Dhaval. Could you share a Workflow for it as well?

Hey, I've shared the app and workflow for Qualys on shuffler. Do you want me to share here in this repo as well?

**Comment by frikky** [comment]
Sure - any reference in general is pretty good. Just paste a link here somewhere for now is fine :)

**Comment by dhaval055** [comment]
> Sure - any reference in general is pretty good. Just paste a link here somewhere for now is fine :)

Here is [link](https://shuffler.io/workflows/e76b144e-f2ed-46a6-aedd-b4186245803e) to the sample workflow.

**Pull request merged**
